### ISSUE TITLE
Configurable `Mappable` table for storage backed trees

### ISSUE THREAD

**Issue by bvrooman** [FuelLabs/fuel-merkle#128]
`fuel-merkle` trees are generic over a `StorageType` type, but `StorageType` is currently hardcoded specifically to the `Mappable` table `NodesTable`, i.e.:

```rust
impl<StorageType, StorageError> MerkleTree<StorageType>
where
    StorageType: StorageMutate<NodesTable, Error = StorageError>,
...
```

The `Mappable` type used to monomorphize `StorageType: StorageMutate<Mappable>` must be configurable so that library users can configure the table.

**Comment by xgreenx** [comment]
I think `MerkleTree` should be generic over the `Mappable` type and `StorageType`. Because key and value types are different for different `Mappable` types and implementation should also be different.

As an alternative, we can introduce a new trait required by `MerkleTree` for `Mappable::Key` and `Mappable::Value` to provide a blanket implementation.

**Comment by bvrooman** [comment]
Yea, I think that may be the simplest solution, and I am trying that out now.
WIP PR here: https://github.com/FuelLabs/fuel-merkle/pull/129

**Comment by bvrooman** [comment]
Because we are defining database storage schemas, I think this work also depends on https://github.com/FuelLabs/fuel-merkle/issues/113. We need a consistent storage solution now so that we can avoid breaking changes in the future. In the WIP PR above, I am exposing the BMT `Node` so that we can create tables of it in `fuel-core`. However, this leaks information to fuel-core that should remain internal to `fuel-merkle`. I think something like a Node facade would work better here.
